### ISSUE TITLE
Passing ACL explicitly doesn't work in 2.x

### ISSUE THREAD

**Issue by roman-eonx** [thephpleague/flysystem-aws-s3-v3#259]
After switching from 1.x to 2.x (2.0.5) the following Symfony config has stopped working correctly (the `bucket-owner-full-control` permission is not applied to the uploaded file):
```yaml
flysystem:
    storages:
        whatever_storage:
            adapter: 'aws'
            options:
                bucket: 'whatever'
                client: 'aws.s3'
                options:
                    ACL: 'bucket-owner-full-control'
```

It looks like 2.x doesn't respect `ACL` given in the config anymore and replaces it with its own ACL option.

Is it intentional behavior? How else could we apply `bucket-owner-full-control`?
