### ISSUE TITLE
Certificate Issue in V3

### ISSUE THREAD

**Issue by thiduzz** [thephpleague/flysystem-aws-s3-v3#26]
I was working on a project locally with v2 but since i upgraded to v3 - I am getting this error:

S3Exception in WrappedHttpHandler.php line 152:
Error executing "HeadObject" on "https://s3-sa-east-1.amazonaws.com/gambero/user_files"; AWS HTTP error: cURL error 60: Peer certificate cannot be authenticated with given CA certificates

The odd thing is that if i run the same thing on v2, on the same local server - it works pretty well.
Is there any way to disable the ssl check in v3?

**Comment by frankdejonge** [comment]
The aws docs suggest updating the certificate: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/faq.html#what-do-i-do-about-a-curl-ssl-certificate-error
From flysystem's end there's really not much I can do. Perhaps open an issue on the sdk repo?

**Comment by frankdejonge** [comment]
I'll close this issue since it's not solvable from this end.

**Comment by apit** [comment]
anyone come to this issue because similar problem in laravel trying to connect to local installation of minio with self-signed certificate, you can update your filesystems.php like this:

```php
's3' => [
  ...
  'use_path_style_endpoint' => true,
  'http_handler' => new App\GuzzleHandler(),
];
```

with GuzzleHandler.php is 
```php
namespace App;
use GuzzleHttp\Client;
use Aws\Handler\GuzzleV6\GuzzleHandler as BaseAwsGuzzleHandler;

class GuzzleHandler extends BaseAwsGuzzleHandler
{
    public function __construct()
    {
        parent::__construct(new Client(
            ['verify' => false]
        ));
    }
}
```

**Comment by rubenrubiob** [comment]
For those coming to look for a Symfony alternative to develop locally, you can define your client this way:

```yml
    Aws\S3\S3Client:
        arguments:
            -   version: 'latest'
                endpoint: '%aws_s3_endpoint%'
                region: '%aws_s3_bucket_region%'
                use_path_style_endpoint: true
                credentials:
                    key: '%aws_s3_access_key%'
                    secret: '%aws_s3_secret_key%'
                http: { verify: false } }
```

The important thing to note is the `http: { verify: false } }`, that disables the peer verification. It is somehow documented in the [`Aws\AwsClient` constructor](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.AwsClient.html#___construct)

Please, take into account that this configuration should only be enabled in a local environment, never in a production system.
