### ISSUE TITLE
S3 ListContents not showing items

### ISSUE THREAD

**Issue by lbcd** [thephpleague/flysystem-aws-s3-v3#320]
I have a fresh minio container : 
- minio/minio:RELEASE.2023-05-18T00-05-36Z

I configure a bucket named "espace-client". Uploaded a file `unnamed.jpg`
I use root account to avoid rights issue.

I have a Symfony project. 
Services :

```
  mys3client:
    class: Aws\S3\S3Client
    arguments:
      - version: 'latest'
        region: 'eu-central-1'
        endpoint: '%env(EC_CA_MINIO_ENDPOINT)%'
        credentials:
          key: '%env(EC_CA_MINIO_USER)%'
          secret: '%env(EC_CA_MINIO_SECRET)%'

  Aws\S3\S3Client:
    alias: mys3client
```

And really basic code in controller:

```

        // The internal adapter
        /** @var FilesystemAdapter $adapter */
        $adapter = new AwsS3V3Adapter(
            $this->mys3client,
            'espace-client'
        );

        // The FilesystemOperator
        $filesystem = new \League\Flysystem\Filesystem($adapter);

        dump($filesystem->read('espace-client/'));
        foreach ($filesystem->listContents('espace-client/', true) as $file) {
            dump($file);
        }

        dump($filesystem->fileExists('espace-client/unnamed.jpg'));

        dump('End');

        die();
```

Result: 

![image](https://github.com/thephpleague/flysystem-aws-s3-v3/assets/1815136/dafc27f9-89d8-470c-9d24-94ae9cd7b32e)

Everything work instead `listContents` that is my first need.

**Comment by lbcd** [comment]
I found the solution

```
    mys3client:
        class: Aws\S3\S3Client
        arguments:
            - version: 'latest'
              region: 'eu-central-1'
              endpoint: 'http://minio:9000'
              use_path_style_endpoint: true
```
  **use_path_style_endpoint: true**
