### ISSUE TITLE
New uploads are not public

### ISSUE THREAD

**Issue by paulcanning** [thephpleague/flysystem-aws-s3-v3#73]
Doing a new upload, even to a folder that is public, is not made public.

How can I set all upload to be publicly accessible?

**Comment by frankdejonge** [comment]
You can give the ['visibility' => 'public'] option in the adapter's constructor, but it's also possible to configure the bucket properties in AWS to be publicly accessible.

**Comment by paulcanning** [comment]
So

```
$client = new S3Client([
    'credentials' => [
        'key'    => '',
        'secret' => ''
    ],
    'region' => 'eu-west-1',
    'version' => 'latest',
    'scheme' => 'http'
    'visibility' => 'public'
]);
```

?

**Comment by frankdejonge** [comment]
@paulcanning no, when you create the adapter, like this:

```php
$adapter = new AwsS3Adapter($client, $bucket, $prefix, ['visibility' => 'public']);
```

**Comment by paulcanning** [comment]
Oh. I think my way worked anyway!

**Comment by slipszenko** [comment]
For anyone else arriving here from Google that is struggling with Digital Ocean spaces files only showing up as private, I got the files that I put into the DO space to display as public with these settings:

```php
$client = new S3Client([
    'endpoint' => 'https://ams3.digitaloceanspaces.com',
    'credentials' => [
        'key'    => \OBJECT_STORE_KEY,
        'secret' => \OBJECT_STORE_SECRET,
    ],
    'region' => 'ams3',
    'version' => 'latest',
]);

$adapter = new AwsS3Adapter($client, 'your_space_name', '', ['ACL' => 'public-read']);

$this->filesystem = new Filesystem($adapter);
```

(Sorry if this isn't the place for this, and if this isn't the correct way to do this.)

**Comment by maniekx1984** [comment]
@slipszenko  mayby you used it with vich/one-up flysystem? When I use ACL: public-read in yaml config file it doesn't work without any error.

**Comment by ThomasBerends** [comment]
And for people arriving here using Symfony, your adapter looks like this:

`
oneup_flysystem:
    adapters:
        default_adapter:
            awss3v3:
                client: [client service name here]
                bucket: '[bucket or spaces name here]'
                options:
                  ACL: 'public-read'
`

**Comment by checcoux** [comment]
I'm using fm-elfinder-bundle with Symfony, this is my config:

```
connector:
      roots:
          uploads:
              driver: Flysystem
              flysystem:
                  type: aws_s3_v3
                  options:
                      aws_s3_v3:
                          endpoint: 'https://r1-it.[xxx].it'
                          version: 'latest'
                          key: '[xxx]'
                          secret: '[xxx]'
                          region: 'r1-it'
                          bucket_name: '[xxx]'
                          options:
                              ACL: 'public-read'
              upload_allow: [ 'image/png', 'image/jpg', 'image/jpeg' ]
              upload_deny: [ 'all' ]
```

but php give me this exception:

> Argument 1 passed to Aws\Common\Client\AbstractClient::__construct() must be an instance of Aws\Common\Credentials\CredentialsInterface, array given, called in /project/vendor/helios-ag/fm-elfinder-bundle/src/Configuration/ElFinderConfigurationReader.php on line 242

**Comment by cedricgeffroy** [comment]
I use VichUploader with Flysystem on a DigitalOcean Space and this is what worked for me:
Note the **visibility: 'public'**

**app/config/packages/flysystem.yaml**
```
services:
    digitalocean_spaces_client:
        class: 'AsyncAws\S3\S3Client'
        arguments:
            -  endpoint: '%env(DO_S3_ENDPOINT)%'
               region: 'ams3'
               accessKeyId: '%env(DO_S3_ACCESS_ID)%'
               accessKeySecret: '%env(DO_S3_ACCESS_SECRET)%'

flysystem:
    storages:
        images.storage:
            adapter: 'asyncaws'
            visibility: 'public'
            options:
                client: 'digitalocean_spaces_client'
                bucket: '%env(DO_S3_BUCKET)%'
```

**app/config/packages/vich_uploader.yaml**
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        images:
            uri_prefix: https://xxxxxxx.ams3.digitaloceanspaces.com
            upload_destination: images.storage
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: { chars_per_dir: 2, dirs: 3 }
